title: <p align="center"> Rajamanickam K </p>
logo: /assets/img/Rajamanickam K.jpg

description:
  <p align="center">
  <a href="https://github.com/rajaanr7">GitHub</a>
  
  <br>   
  I'm working on Data Science Professional mainly on Big Data, Spark
  <br>
  </p>



theme: jekyll-theme-minimal
